export const EXTENSION_NAME = 'ST-Little Painter';
export const EXTENSION_ID = 'ST-Little_Painter';
export const SETTINGS_KEY = 'ST-Little_Painter';
export const TRACE_LIMIT = 20;

export const SELECTORS = Object.freeze({
  settingsRoot: '#st-little-painter-settings',
  enabled: '#stlp-enabled',
  autoGenerate: '#stlp-auto-generate',
  mode: '#stlp-mode',
  tagApiUrl: '#stlp-tag-api-url',
  tagApiKey: '#stlp-tag-api-key',
  tagApiModel: '#stlp-tag-api-model',
  backendEnabled: '#stlp-backend-enabled',
  backendType: '#stlp-backend-type',
  sdWebuiUrl: '#stlp-sdwebui-url',
  sdWebuiUsername: '#stlp-sdwebui-username',
  sdWebuiPassword: '#stlp-sdwebui-password',
  sdWebuiWidth: '#stlp-sdwebui-width',
  sdWebuiHeight: '#stlp-sdwebui-height',
  sdWebuiSteps: '#stlp-sdwebui-steps',
  sdWebuiCfgScale: '#stlp-sdwebui-cfg-scale',
  sdWebuiSampler: '#stlp-sdwebui-sampler',
  sdWebuiSeed: '#stlp-sdwebui-seed',
  sdWebuiRestoreFaces: '#stlp-sdwebui-restore-faces',
  sdWebuiSendNegative: '#stlp-sdwebui-send-negative',
  novelaiUrl: '#stlp-novelai-url',
  novelaiApiKey: '#stlp-novelai-api-key',
  novelaiModel: '#stlp-novelai-model',
  novelaiSampler: '#stlp-novelai-sampler',
  novelaiScheduler: '#stlp-novelai-scheduler',
  novelaiWidth: '#stlp-novelai-width',
  novelaiHeight: '#stlp-novelai-height',
  novelaiSteps: '#stlp-novelai-steps',
  novelaiScale: '#stlp-novelai-scale',
  novelaiSeed: '#stlp-novelai-seed',
  novelaiNegativePrompt: '#stlp-novelai-negative-prompt',
  comfyuiUrl: '#stlp-comfyui-url',
  comfyuiWorkflowJson: '#stlp-comfyui-workflow-json',
  comfyuiWidth: '#stlp-comfyui-width',
  comfyuiHeight: '#stlp-comfyui-height',
  comfyuiSteps: '#stlp-comfyui-steps',
  comfyuiCfg: '#stlp-comfyui-cfg',
  comfyuiSeed: '#stlp-comfyui-seed',
  comfyuiSampler: '#stlp-comfyui-sampler',
  comfyuiScheduler: '#stlp-comfyui-scheduler',
  comfyuiModel: '#stlp-comfyui-model',
  comfyuiPollIntervalMs: '#stlp-comfyui-poll-interval-ms',
  comfyuiMaxPolls: '#stlp-comfyui-max-polls',
  naturalImageProviderMode: '#stlp-natural-image-provider-mode',
  naturalImageUrl: '#stlp-natural-image-url',
  naturalImageApiKey: '#stlp-natural-image-api-key',
  naturalImageModel: '#stlp-natural-image-model',
  naturalImageChatModel: '#stlp-natural-image-chat-model',
  naturalImageSize: '#stlp-natural-image-size',
  naturalImageWidth: '#stlp-natural-image-width',
  naturalImageHeight: '#stlp-natural-image-height',
  naturalImageQuality: '#stlp-natural-image-quality',
  naturalImageResponseFormat: '#stlp-natural-image-response-format',
  naturalImageInstructionPrefix: '#stlp-natural-image-instruction-prefix',
  naturalImageInstructionSuffix: '#stlp-natural-image-instruction-suffix',
  historyCount: '#stlp-history-count',
  temperature: '#stlp-temperature',
  maxTokens: '#stlp-max-tokens',
  timeoutMs: '#stlp-timeout-ms',
  retryCount: '#stlp-retry-count',
  debugEnabled: '#stlp-debug-enabled',
  manualGenerate: '#stlp-manual-generate',
  exportTrace: '#stlp-export-trace',
  traceOutput: '#stlp-trace-output',
  imagePreviewList: '#stlp-image-preview-list',
  wandButton: '#stlp-wand-button',
  consoleRoot: '#stlp-console-root',
  consoleClose: '#stlp-console-close',
  consoleBackdrop: '#stlp-console-backdrop',
  consoleTabs: '[data-stlp-console-tab]',
  consoleTabPanels: '[data-stlp-console-panel]',
});

export const TRACE_STATUS = Object.freeze({
  RUNNING: 'running',
  SUCCESS: 'success',
  ERROR: 'error',
});
